CREATE TABLE MEMBER(
MEMBER_ID VARCHAR(20) NOT NULL,
MEMBER_PW VARCHAR(20) NOT NULL,
MEMBER_TYPE VARCHAR(10) DEFAULT ‘MEMBER’,
MEMBER_NAME VARCHAR(10) NOT NULL,
MEMBER_PH CHAR(10) NOT NULL,
PRIMARY KEY(MEMBER_ID),
CHECK(MEMBER_TYPE IN ('ADMIN','MEMBER'))
);

INSERT INTO MEMBER
VALUES('ADMIN','1234','ADMIN','ADMIN','021234567');
INSERT INTO MEMBER
VALUES('USER1','1234','MEMBER','HONG','023456789');
INSERT INTO MEMBER
VALUES('USER2','1234','MEMBER','KANG','024567890');

create table NOTICE(
   NOTICE_INDEX int,
   TITLE varchar(200),
   WRITER varchar(20),
   CONTENTS varchar(4000),
   NOTICE_DATE date default sysdate,
   NOTICE_HITS int default 0,
   PRIMARY KEY(NOTICE_INDEX));
   
INSERT INTO NOTICE(NOTICE_INDEX,TITLE,WRITER,CONTENTS)
VALUES(1,'공지사항TEST1','ADMIN','TEST1');
INSERT INTO NOTICE(NOTICE_INDEX,TITLE,WRITER,CONTENTS)
VALUES(2,'공지사항TEST2','ADMIN','TEST2');

create table APPLY(
   APPLY_INDEX int,
   APPLY_SORT VARCHAR(10),
   APPLY_ID VARCHAR(20),
   APPLY_DATE date default sysdate,
   LOCATION VARCHAR(30),
   ANI_NAME VARCHAR(20),
   ANI_TYPE VARCHAR(30),
   ANI_BLOODTYPE VARCHAR(30),
   ANI_GENDER VARCHAR(10),
   ANI_AGE INT,
   RESULT VARCHAR(20),
   PRIMARY KEY(APPLY_INDEX),
CHECK(ANI_AGE >= 0)
);

INSERT INTO APPLY(APPLY_INDEX,APPLY_SORT,APPLY_ID,LOCATION,ANI_NAME,ANI_TYPE,ANI_BLOODTYPE,ANI_GENDER,ANI_AGE,RESULT)
VALUES(1,'수혈','ADMIN','경기','멍걸이','풍산개','1.1','MALE',3,'WAITING');
INSERT INTO APPLY(APPLY_INDEX,APPLY_SORT,APPLY_ID,LOCATION,ANI_NAME,ANI_TYPE,ANI_BLOODTYPE,ANI_GENDER,ANI_AGE,RESULT)
VALUES(2,'헌혈','USER1','강원','카누','리트리버','1','MALE',2,'WAITING');